/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package udea.edu.com.co.programa.dos;

import java.io.IOException;
import static java.lang.Math.pow;
import javax.swing.JOptionPane;

/**
 *
 * @author Romero-Pc
 */
public class ProgramaDosGUI extends javax.swing.JFrame {

    GestionDatos programa = new GestionDatos();
    ListaLigada columnaX;
    ListaLigada columnaY;
    Double nodoData;
    double B0;
    double B1;
    double[][] resultados;
    
    /**
     * Creates new form ProgramaDosGUI
     */
    public ProgramaDosGUI() {
        initComponents();
        this.labelYk.setVisible(false);
        this.textYk.setVisible(false);
        this.btnCalcularYk.setVisible(false);
        this.labelResultYk.setVisible(false);
        this.textResultYk.setVisible(false);
        this.btnCalcular.setEnabled(false);
        this.btnGraficar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnX = new javax.swing.JButton();
        btnY = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaColumnaY = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaColumnaX = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textBeta0 = new javax.swing.JTextField();
        btnGraficar = new javax.swing.JButton();
        textBeta1 = new javax.swing.JTextField();
        textErreXY = new javax.swing.JTextField();
        textErre2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textYk = new javax.swing.JTextField();
        labelYk = new javax.swing.JLabel();
        textResultYk = new javax.swing.JTextField();
        btnCalcularYk = new javax.swing.JButton();
        labelResultYk = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnX.setText("Columna X");
        btnX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXActionPerformed(evt);
            }
        });

        btnY.setText("Columna Y");
        btnY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYActionPerformed(evt);
            }
        });

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        textAreaColumnaY.setEditable(false);
        textAreaColumnaY.setRows(5);
        jScrollPane1.setViewportView(textAreaColumnaY);

        textAreaColumnaX.setEditable(false);
        textAreaColumnaX.setRows(5);
        jScrollPane2.setViewportView(textAreaColumnaX);

        jLabel3.setText("Beta 0");

        jLabel4.setText("Beta 1");

        textBeta0.setEditable(false);
        textBeta0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBeta0ActionPerformed(evt);
            }
        });

        btnGraficar.setText("Graficar");

        textBeta1.setEditable(false);
        textBeta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBeta1ActionPerformed(evt);
            }
        });

        textErreXY.setEditable(false);
        textErreXY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textErreXYActionPerformed(evt);
            }
        });

        textErre2.setEditable(false);
        textErre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textErre2ActionPerformed(evt);
            }
        });

        jLabel5.setText("r(x,y)");

        jLabel6.setText("r^2");

        textYk.setText(" ");
        textYk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textYkActionPerformed(evt);
            }
        });

        labelYk.setText("X(k)");

        textResultYk.setEditable(false);
        textResultYk.setText(" ");
        textResultYk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textResultYkActionPerformed(evt);
            }
        });

        btnCalcularYk.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        btnCalcularYk.setText("Calcular Y(k)");
        btnCalcularYk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularYkActionPerformed(evt);
            }
        });

        labelResultYk.setText("Resultado Y(k)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addComponent(textBeta0, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textBeta1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textErreXY, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textErre2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelResultYk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textResultYk, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCalcularYk)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelYk)
                                .addGap(47, 47, 47)
                                .addComponent(textYk, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(103, 103, 103))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(btnX)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnY)
                                .addGap(94, 94, 94))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(btnCalcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGraficar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(textBeta0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textBeta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textErreXY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textErre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textYk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelYk))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCalcularYk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textResultYk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelResultYk))))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnX)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnY)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular)
                    .addComponent(btnGraficar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXActionPerformed
        this.textAreaColumnaX.setText("");
        try {
            columnaX = programa.leerDatos(",");
           int size = columnaX.getTamano(); 
            for (int i = 0; i < size; i++) {
                nodoData = columnaX.getNodo(i).getDato();
                this.textAreaColumnaX.append(nodoData+ "\n");
            }
            if (columnaY != null && columnaY.getTamano() != 0) {
                this.btnCalcular.setEnabled(true);
                this.btnGraficar.setEnabled(true);
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al abrir el archivo", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnXActionPerformed

    private void btnYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYActionPerformed
        this.textAreaColumnaY.setText("");
        try {
            columnaY = programa.leerDatos(",");
            int size = columnaY.getTamano();
            for (int i = 0; i < size; i++) {
                nodoData = columnaY.getNodo(i).getDato();
                this.textAreaColumnaY.append(nodoData + "\n");
            }
            if (columnaX != null && columnaX.getTamano()!= 0) {
                this.btnCalcular.setEnabled(true);
                this.btnGraficar.setEnabled(true);
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al abrir el archivo", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnYActionPerformed

    private void textBeta0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBeta0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBeta0ActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        B0 = Calculos.calcularBetaCero(columnaX, columnaY);
        B1 = Calculos.calcularBetaUno(columnaX, columnaY);
        double r = Calculos.calcularR(columnaX, columnaY);
        
        B0 = Calculos.roundDouble(B0, 4);
        B1 = Calculos.roundDouble(B1, 4);
        r = Calculos.roundDouble(r, 4);
        double rCuadrado = Calculos.roundDouble(pow(r,2), 4);
        
        this.textBeta0.setText(String.valueOf(B0));
        this.textBeta1.setText(String.valueOf(B1));
        this.textErreXY.setText(String.valueOf(r));
        this.textErre2.setText(String.valueOf(rCuadrado));
        
        this.labelYk.setVisible(true);
        this.textYk.setVisible(true);
        this.btnCalcularYk.setVisible(true);
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void textBeta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBeta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBeta1ActionPerformed

    private void textErreXYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textErreXYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textErreXYActionPerformed

    private void textErre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textErre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textErre2ActionPerformed

    private void btnCalcularYkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularYkActionPerformed
        double dato=0;
        if (!this.textYk.getText().equals("")) {
            try {
                dato = Double.parseDouble(this.textYk.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Por favor ingrese un valor numérico con formato ###.####");
            }
            double resultYk = Calculos.calcularYk(B0, B1, dato);
            
            resultYk = Calculos.roundDouble(resultYk, 4);
            
            this.labelResultYk.setVisible(true);
            this.textResultYk.setVisible(true);
            this.textResultYk.setText(String.valueOf(resultYk));
            
        }
    }//GEN-LAST:event_btnCalcularYkActionPerformed

    private void textYkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textYkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textYkActionPerformed

    private void textResultYkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textResultYkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textResultYkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgramaDosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgramaDosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgramaDosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgramaDosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgramaDosGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCalcularYk;
    private javax.swing.JButton btnGraficar;
    private javax.swing.JButton btnX;
    private javax.swing.JButton btnY;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel labelResultYk;
    private javax.swing.JLabel labelYk;
    private javax.swing.JTextArea textAreaColumnaX;
    private javax.swing.JTextArea textAreaColumnaY;
    private javax.swing.JTextField textBeta0;
    private javax.swing.JTextField textBeta1;
    private javax.swing.JTextField textErre2;
    private javax.swing.JTextField textErreXY;
    private javax.swing.JTextField textResultYk;
    private javax.swing.JTextField textYk;
    // End of variables declaration//GEN-END:variables
}
